export const mockNotifications = [
  {
    id: 1,
    title: "Welcome to app IFriend",
    description: "Protect your child through IFriend",
    type: "Success",
    action: "Automatic",
  },
  {
    id: 2,
    title: "Limited Time Offer! 35% Off Limited Time Offer! 35% Off Limited Time Offer! 35% Off",
    description: "Get 35% off on the monthly plan now! This offer is valid for a limited time only. Get 35% off on the monthly plan now! This offer is valid for a limited time only. Get 35% off on the monthly plan now! This offer is valid for a limited time only. Get 35% off on the monthly plan now! This offer is valid for a limited time only. Get 35% off on the monthly plan now! This offer is valid for a limited time only. Get 35% off on the monthly plan now! This offer is valid for a limited time only. Get 35% off on the monthly plan now! This offer is valid for a limited time only. Get 35% off on the monthly plan now! This offer is valid for a limited time only.",
    type: "Success",
    action: "Manual",
  },
  {
    id: 3,
    title: "Profile Update Reminder",
    description: "Your profile information hasn't been updated in a while. Please review it.",
    type: "Review",
    action: "Automatic",
  },
  {
    id: 4,
    title: "New Friend Request",
    description: "You have a new friend request from John Doe.",
    type: "Info",
    action: "Manual",
  },
  {
    id: 5,
    title: "Security Alert",
    description: "A new login was detected from a new device.",
    type: "Warning",
    action: "Automatic",
  },
  {
    id: 6,
    title: "Payment Successful",
    description: "Your payment of $15.00 has been successfully processed.",
    type: "Success",
    action: "Automatic",
  },
  {
    id: 7,
    title: "Subscription Expiring",
    description: "Your subscription will expire in 3 days. Renew now to avoid interruption.",
    type: "Warning",
    action: "Automatic",
  },
  {
    id: 8,
    title: "New Feature Available",
    description: "Check out the new location tracking feature in the settings.",
    type: "Success",
    action: "Manual",
  },
  {
    id: 9,
    title: "Maintenance Scheduled",
    description: "Scheduled maintenance on Sunday, 12:00 AM - 4:00 AM.",
    type: "Info",
    action: "Automatic",
  },
  {
    id: 10,
    title: "Feedback Request",
    description: "We'd love to hear your thoughts on our latest update.",
    type: "Review",
    action: "Manual",
  },
  {
    id: 11,
    title: "Account Verified",
    description: "Your email address has been successfully verified.",
    type: "Success",
    action: "Automatic",
  },
  {
    id: 12,
    title: "Suspicious Activity",
    description: "We detected suspicious activity on your account. Please change your password.",
    type: "Warning",
    action: "Automatic",
  },
  {
    id: 13,
    title: "Weekly Summary",
    description: "Here is your weekly activity summary.",
    type: "Info",
    action: "Automatic",
  },
  {
    id: 14,
    title: "Points Redeemed",
    description: "You have successfully redeemed 500 points for a discount coupon.",
    type: "Success",
    action: "Manual",
  },
  {
    id: 15,
    title: "System Update",
    description: "System update v2.0.1 has been installed successfully.",
    type: "Info",
    action: "Automatic",
  },
];
